cache:
    page:
        enable: false
    data:
        enable: false
display_load_time: true
theme: default
nice_urls: true
twig:
    debug: true
plugins:
    path: /web/www/getherbie/plugins/
    enable:
        - adminpanel
        - random
        - simplecontact
        - xmlsitemap
        - rssfeed
        - simplesearch
        - lipsum
        - test
        - vimeo
        - youtube
        - googlemaps
        - disqus
        - highlight
        - shortcode
        - imagine
        - gist
    config:
        simplesearch:
            use_page_cache: true
