app:
  path: APP_PATH

site:
  path: SITE_PATH

data:
  path: SITE_PATH/data
  extensions: [yml, yaml]

layouts:
  path: SITE_PATH/layouts

pages:
  path: SITE_PATH/pages

posts:
  path: SITE_PATH/posts

nice_urls: true

twig:
  debug: false
  cache: false

cache:
  page:
    enable: false
    dir: SITE_PATH/cache/page
    expire: 18000
  data:
    enable: false
    dir: SITE_PATH/cache/data
    expire: 18000

pseudo_html:
  from: <box>|</box>|<box:info>|</box:info>
  to: <div class="pure-u-1-2 box box-1"><div markdown="1">|</div></div>|<div class="box box-info" markdown="1">|</div>

charset: utf-8
language: de
locale: de_DE