cache:
    page:
        enable: false
    data:
        enable: true

display_load_time: true
theme: default
nice_urls: true
twig:
    debug: true
plugins:
    path: /web/www/getherbie/plugins/
    enable:
        #- adminpanel
        - random
        - simplecontact
        - xmlsitemap
        - feed
        - simplesearch
        - lipsum
        - test
        - googlemaps
        - disqus
        - highlight
        - imagine
        - gist
        - grid
        - video
        - redirect
        - smartypants
        - menu
    config:
        simplesearch:
            use_page_cache: true
        disqus:
            twig: true
